//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrackSoft.RegExplore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrackSoft.RegExplore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected entries?.
        /// </summary>
        internal static string Confirm_DeleteEntries {
            get {
                return ResourceManager.GetString("Confirm_DeleteEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this key and all of its subkeys?.
        /// </summary>
        internal static string Confirm_DeleteKey {
            get {
                return ResourceManager.GetString("Confirm_DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these values?.
        /// </summary>
        internal static string Confirm_DeleteValue {
            get {
                return ResourceManager.GetString("Confirm_DeleteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a favorite with that name..
        /// </summary>
        internal static string Error_AlreadyFavorite {
            get {
                return ResourceManager.GetString("Error_AlreadyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create key: Error writing to the registry..
        /// </summary>
        internal static string Error_CreateKeyFail {
            get {
                return ResourceManager.GetString("Error_CreateKeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create value: Error writing to the registry..
        /// </summary>
        internal static string Error_CreateValueFail {
            get {
                return ResourceManager.GetString("Error_CreateValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some entries could not be deleted..
        /// </summary>
        internal static string Error_DeleteEntriesFail {
            get {
                return ResourceManager.GetString("Error_DeleteEntriesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the specified key..
        /// </summary>
        internal static string Error_DeleteKeyFail {
            get {
                return ResourceManager.GetString("Error_DeleteKeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some values could not be deleted..
        /// </summary>
        internal static string Error_DeleteValueFail {
            get {
                return ResourceManager.GetString("Error_DeleteValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error exporting the file..
        /// </summary>
        internal static string Error_ExportFail {
            get {
                return ResourceManager.GetString("Error_ExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the file..
        /// </summary>
        internal static string Error_FileOpenFail {
            get {
                return ResourceManager.GetString("Error_FileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registry key specified..
        /// </summary>
        internal static string Error_InvalidKey {
            get {
                return ResourceManager.GetString("Error_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete..
        /// </summary>
        internal static string Info_ExportSuccess {
            get {
                return ResourceManager.GetString("Info_ExportSuccess", resourceCulture);
            }
        }
    }
}
